variable "aws_region" {
  description = "AWS region for all resources."
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment tag value."
  type        = string
  default     = "DEV"
}

variable "owner" {
  description = "Owner tag value."
  type        = string
  default     = "PlatformTeam"
}

variable "cost_center" {
  description = "Cost center tag value."
  type        = string
  default     = "IT-Infra"
}

variable "additional_tags" {
  description = "Additional tags to apply to resources."
  type        = map(string)
  default     = {}
}

variable "s3_bucket_name" {
  description = "Destination archive bucket name."
  type        = string
  default     = "dev-was-log-archive"
}

variable "enable_object_lock" {
  description = "Enable S3 Object Lock for immutable retention (must be set only at bucket creation)."
  type        = bool
  default     = false
}

variable "enable_s3_access_logging" {
  description = "Enable S3 server access logging for archive bucket."
  type        = bool
  default     = false
}

variable "s3_access_log_bucket_name" {
  description = "Optional dedicated access log bucket name. Required only when enable_s3_access_logging=true."
  type        = string
  default     = ""
}

variable "kms_alias_name" {
  description = "KMS alias for archive encryption key."
  type        = string
  default     = "alias/dev-was-log-archive-kms"
}

variable "source_environment" {
  description = "Source environment type: ec2 or onprem."
  type        = string
  default     = "ec2"

  validation {
    condition     = contains(["ec2", "onprem"], var.source_environment)
    error_message = "source_environment must be ec2 or onprem."
  }
}

variable "source_type" {
  description = "Source protocol for DataSync location: NFS or SMB."
  type        = string
  default     = "NFS"

  validation {
    condition     = contains(["NFS", "SMB"], var.source_type)
    error_message = "source_type must be NFS or SMB."
  }
}

variable "source_server_hostname" {
  description = "Source server DNS/IP reachable by DataSync agent."
  type        = string
}

variable "source_subdirectory" {
  description = "Source log root path exposed by NFS/SMB, for example /logs/."
  type        = string
  default     = "/logs/"
}

variable "nfs_version" {
  description = "NFS mount version for source location."
  type        = string
  default     = "AUTOMATIC"
}

variable "smb_domain" {
  description = "SMB domain (used only when source_type=SMB)."
  type        = string
  default     = ""
}

variable "smb_username" {
  description = "SMB username (used only when source_type=SMB)."
  type        = string
  default     = ""
}

variable "smb_password" {
  description = "SMB password (used only when source_type=SMB)."
  type        = string
  default     = ""
  sensitive   = true
}

variable "datasync_s3_subdirectory" {
  description = "Destination S3 prefix for DataSync writes, e.g. /hostname/yyyy/mm/dd/."
  type        = string
  default     = "/"
}

variable "datasync_agent_activation_key" {
  description = "Activation key generated by the DataSync agent console."
  type        = string
  sensitive   = true
}

variable "datasync_task_name" {
  description = "Name of the DataSync task."
  type        = string
  default     = "dev-was-logs-daily-archive"
}

variable "datasync_schedule_expression" {
  description = "DataSync schedule expression; default is daily 1AM UTC."
  type        = string
  default     = "cron(0 1 * * ? *)"
}

variable "include_filters" {
  description = "List of SIMPLE_PATTERN include filters (recommend compressed rotated files only, e.g. *.gz)."
  type        = list(string)
  default     = ["*.gz"]
}

variable "bandwidth_limit_bps" {
  description = "Max transfer rate in bytes/sec; -1 for unlimited."
  type        = number
  default     = -1
}

variable "create_ec2_agent" {
  description = "Create EC2 host for DataSync agent (for VPC-based source patterns)."
  type        = bool
  default     = false
}

variable "datasync_agent_ami_id" {
  description = "DataSync agent AMI ID (required when create_ec2_agent=true)."
  type        = string
  default     = ""
}

variable "datasync_agent_instance_type" {
  description = "EC2 instance type for DataSync agent host."
  type        = string
  default     = "m5.large"
}

variable "vpc_id" {
  description = "VPC ID for agent networking and optional S3 gateway endpoint."
  type        = string
  default     = ""
}

variable "private_subnet_id" {
  description = "Private subnet ID for DataSync agent EC2 instance."
  type        = string
  default     = ""
}

variable "private_route_table_ids" {
  description = "Private route table IDs for S3 gateway endpoint association."
  type        = list(string)
  default     = []
}

variable "source_cidr_blocks" {
  description = "Source storage CIDRs reachable by the DataSync agent."
  type        = list(string)
  default     = []
}

variable "create_s3_gateway_endpoint" {
  description = "Create S3 Gateway VPC endpoint for private traffic from EC2 DataSync agent."
  type        = bool
  default     = false
}

variable "enable_sns_alerting" {
  description = "Enable SNS topic and subscriptions for alarms."
  type        = bool
  default     = true
}

variable "sns_email_endpoints" {
  description = "Email addresses for SNS subscriptions."
  type        = list(string)
  default     = []
}

variable "minimum_expected_bytes_daily" {
  description = "Lower threshold for daily bytes transferred alarm."
  type        = number
  default     = 30000000000
}

variable "enable_cloudtrail" {
  description = "Enable CloudTrail data/audit logging for governance."
  type        = bool
  default     = true
}

variable "cloudtrail_bucket_name" {
  description = "CloudTrail log bucket name."
  type        = string
  default     = "dev-was-log-archive-cloudtrail"
}